// GDR v1 replay writer (https://github.com/maxnut/GDReplayFormat, branch gdr1).
// Mega Hack v9 reads GDR replays from "<Geometry Dash folder>/replays".
// The same document is written either as msgpack (.gdr) or JSON (.gdr.json).

#include "Macro.hpp"
#include <Geode/Geode.hpp>
#include <cstring>
#include <fstream>

using namespace geode::prelude;

namespace pf::macro {

std::string pathToUtf8(std::filesystem::path const& p) {
    auto u = p.u8string();
    return std::string(reinterpret_cast<char const*>(u.c_str()), u.size());
}

namespace {

// Minimal document writer interface so JSON and msgpack share one schema.
struct Writer {
    virtual ~Writer() = default;
    virtual void beginMap(size_t n) = 0;
    virtual void endMap() = 0;
    virtual void beginArray(size_t n) = 0;
    virtual void endArray() = 0;
    virtual void key(std::string const& k) = 0;
    virtual void str(std::string const& v) = 0;
    virtual void real(double v) = 0;
    virtual void integer(int64_t v) = 0;
    virtual void boolean(bool v) = 0;
};

class JsonWriter : public Writer {
public:
    std::string out;

    void beginMap(size_t) override { value(); out += '{'; m_first.push_back(true); }
    void endMap() override { out += '}'; m_first.pop_back(); }
    void beginArray(size_t) override { value(); out += '['; m_first.push_back(true); }
    void endArray() override { out += ']'; m_first.pop_back(); }
    void key(std::string const& k) override {
        comma();
        quote(k);
        out += ':';
        m_afterKey = true;
    }
    void str(std::string const& v) override { value(); quote(v); }
    void real(double v) override { value(); out += fmt::format("{}", v); }
    void integer(int64_t v) override { value(); out += std::to_string(v); }
    void boolean(bool v) override { value(); out += v ? "true" : "false"; }

private:
    std::vector<bool> m_first;
    bool m_afterKey = false;

    void comma() {
        if (m_first.empty()) return;
        if (!m_first.back()) out += ',';
        m_first.back() = false;
    }
    void value() {
        if (m_afterKey) { m_afterKey = false; return; }
        comma();
    }
    void quote(std::string const& s) {
        out += '"';
        for (char c : s) {
            switch (c) {
                case '"': out += "\\\""; break;
                case '\\': out += "\\\\"; break;
                case '\n': out += "\\n"; break;
                case '\r': out += "\\r"; break;
                case '\t': out += "\\t"; break;
                default:
                    if (static_cast<unsigned char>(c) < 0x20) out += fmt::format("\\u{:04x}", int(c));
                    else out += c;
            }
        }
        out += '"';
    }
};

class MsgpackWriter : public Writer {
public:
    std::vector<uint8_t> out;

    void beginMap(size_t n) override {
        if (n < 16) byte(0x80 | uint8_t(n));
        else if (n < 0x10000) { byte(0xde); be(n, 2); }
        else { byte(0xdf); be(n, 4); }
    }
    void endMap() override {}
    void beginArray(size_t n) override {
        if (n < 16) byte(0x90 | uint8_t(n));
        else if (n < 0x10000) { byte(0xdc); be(n, 2); }
        else { byte(0xdd); be(n, 4); }
    }
    void endArray() override {}
    void key(std::string const& k) override { str(k); }
    void str(std::string const& v) override {
        size_t n = v.size();
        if (n < 32) byte(0xa0 | uint8_t(n));
        else if (n < 0x100) { byte(0xd9); be(n, 1); }
        else if (n < 0x10000) { byte(0xda); be(n, 2); }
        else { byte(0xdb); be(n, 4); }
        out.insert(out.end(), v.begin(), v.end());
    }
    void real(double v) override {
        uint64_t bits;
        std::memcpy(&bits, &v, 8);
        byte(0xcb);
        be(bits, 8);
    }
    void integer(int64_t v) override {
        if (v >= 0 && v < 128) byte(uint8_t(v));
        else if (v >= 0 && v < 0x100) { byte(0xcc); be(uint64_t(v), 1); }
        else if (v >= 0 && v < 0x10000) { byte(0xcd); be(uint64_t(v), 2); }
        else if (v >= 0 && v <= 0xffffffffLL) { byte(0xce); be(uint64_t(v), 4); }
        else if (v >= -32 && v < 0) byte(uint8_t(0xe0 | (v + 32)));
        else { byte(0xd3); be(uint64_t(v), 8); }
    }
    void boolean(bool v) override { byte(v ? 0xc3 : 0xc2); }

private:
    void byte(uint8_t b) { out.push_back(b); }
    void be(uint64_t v, int bytes) {
        for (int i = bytes - 1; i >= 0; i--) out.push_back(uint8_t(v >> (i * 8)));
    }
};

void writeReplay(Writer& w, Info const& info, std::vector<Input> const& inputs) {
    double duration = info.lastTick / info.framerate;

    w.beginMap(15);
    w.key("gameVersion"); w.real(2.2081);
    w.key("description"); w.str("Generated by Pathfinder");
    w.key("version"); w.real(1.0);
    w.key("duration"); w.real(duration);
    w.key("bot");
    w.beginMap(2);
    w.key("name"); w.str("Pathfinder");
    w.key("version"); w.str("2.0.0");
    w.endMap();
    w.key("level");
    w.beginMap(2);
    w.key("id"); w.integer(info.levelID);
    w.key("name"); w.str(info.levelName);
    w.endMap();
    w.key("author"); w.str("Pathfinder");
    w.key("seed"); w.integer(0);
    w.key("coins"); w.integer(0);
    w.key("ldm"); w.boolean(false);
    w.key("platformer"); w.boolean(info.platformer);
    w.key("framerate"); w.real(info.framerate);
    w.key("inputs");
    w.beginArray(inputs.size());
    for (auto const& in : inputs) {
        w.beginMap(4);
        w.key("frame"); w.integer(in.tick);
        w.key("btn"); w.integer(in.button);
        w.key("2p"); w.boolean(in.player2);
        w.key("down"); w.boolean(in.down);
        w.endMap();
    }
    w.endArray();
    // GDR readers ignore unknown keys; keep the map size exact for msgpack
    w.key("pathfinderTicksPerSecond"); w.real(info.framerate);
    w.key("pathfinderInputCount"); w.integer(static_cast<int64_t>(inputs.size()));
    w.endMap();
}

std::string safeFileName(std::string s) {
    for (auto& c : s) {
        if (c == '/' || c == '\\' || c == ':' || c == '*' || c == '?' || c == '"' ||
            c == '<' || c == '>' || c == '|' || static_cast<unsigned char>(c) < 0x20) c = '_';
    }
    while (!s.empty() && (s.back() == ' ' || s.back() == '.')) s.pop_back();
    if (s.empty()) s = "level";
    return s;
}

bool writeFile(std::filesystem::path const& path, void const* data, size_t size, std::string& err) {
    std::error_code ec;
    std::filesystem::create_directories(path.parent_path(), ec);
    std::ofstream f(path, std::ios::binary | std::ios::trunc);
    if (!f) {
        err = fmt::format("Cannot open {} for writing{}", pathToUtf8(path),
            ec ? " (" + ec.message() + ")" : "");
        return false;
    }
    f.write(static_cast<char const*>(data), static_cast<std::streamsize>(size));
    if (!f) {
        err = fmt::format("Failed to write {}", pathToUtf8(path));
        return false;
    }
    return true;
}

} // namespace

ExportResult exportMacro(Info const& info, std::vector<Input> const& inputs,
                         std::filesystem::path const& dir, std::string const& format) {
    ExportResult res;

    JsonWriter json;
    writeReplay(json, info, inputs);
    MsgpackWriter msgpack;
    writeReplay(msgpack, info, inputs);

    bool wantBinary = format == "gdr" || format == "both";
    bool wantJson = format == "gdr.json" || format == "both" || (!wantBinary);

    auto base = safeFileName(info.levelName) + "_pathfinder";

    auto writeTo = [&](std::filesystem::path const& folder, bool report) {
        std::string err;
        if (wantBinary) {
            auto p = folder / (base + ".gdr");
            if (writeFile(p, msgpack.out.data(), msgpack.out.size(), err)) { if (report) res.files.push_back(p); }
            else if (report) res.errors.push_back(err);
        }
        if (wantJson) {
            auto p = folder / (base + ".gdr.json");
            if (writeFile(p, json.out.data(), json.out.size(), err)) { if (report) res.files.push_back(p); }
            else if (report) res.errors.push_back(err);
        }
    };

    writeTo(dir, true);
    // backup copy, so a macro is never lost if the game folder is not writable
    auto backup = Mod::get()->getSaveDir() / "replays";
    if (res.files.empty()) writeTo(backup, true);
    else writeTo(backup, false);

    return res;
}

} // namespace pf::macro
